[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/Users/itd/Training/Ansible/local.pem

# Disables SSH host key verification - skips "Are you sure you want to continue connecting?" prompt
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Specifies which Python interpreter to use on remote hosts (required for systems with only Python 3)
ansible_python_interpreter=/usr/bin/python3

# Privilege Escalation
ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root

# Connection Settings
ansible_connection=ssh
ansible_port=22
ansible_ssh_timeout=30

[production:children]
prod_web_servers
prod_app_servers
prod_db_servers

[staging:children]
stag_web_servers
stag_app_servers
stag_db_servers


[prod_web_servers]
web1 ansible_host=192.168.1.10
web2 ansible_host=192.168.1.11

[prod_app_servers]
app1 ansible_host=192.168.1.20
app2 ansible_host=192.168.1.21

[prod_db_servers]
db1 ansible_host=192.168.1.30


[stag_web_servers]
stag-web1 ansible_host=192.168.2.10

[stag_app_servers]
stag-app1 ansible_host=192.168.2.20

[stag_db_servers]
stag-db1 ansible_host=192.168.2.30