[express_servers]
express1 ansible_host=3.111.53.81

[flask_servers]
flask1 ansible_host=3.110.43.182

[java_servers]
java1 ansible_host=52.66.243.67

[static_servers]
static1 ansible_host=3.108.237.182

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/Users/itd/TEMP/Ansible/dec2025.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
