#!/bin/bash

# Advanced Ad-Hoc Commands Examples
# These demonstrate more complex ad-hoc command usage

echo "🔧 ITD Advanced Ansible Ad-Hoc Commands Examples"
echo "================================================"
echo ""

INVENTORY="inventory/hosts.ini"

echo "1️⃣  Running command with shell features..."
ansible webservers -m shell -a "echo 'Current user: $(whoami)' && echo 'Current directory: $(pwd)' && echo 'Date: $(date)'" -i $INVENTORY
echo ""

echo "2️⃣  Using check mode (dry run)..."
ansible webservers -m file -a "path=/tmp/test-check-mode state=touch" -C -i $INVENTORY
echo ""

echo "3️⃣  Copying content directly (no source file)..."
ansible webservers -m copy -a "content='Generated by Ansible at $(date -Iseconds)' dest=/tmp/timestamp.txt" -i $INVENTORY
echo ""

echo "4️⃣  Running multiple commands with shell..."
ansible webservers -m shell -a "echo '=== System Info ===' && uname -a && echo '' && echo '=== Disk Usage ===' && df -h / | tail -1" -i $INVENTORY
echo ""

echo "5️⃣  Gathering specific facts..."
ansible webservers -m setup -a "filter=ansible_processor*" -i $INVENTORY
echo ""

echo "6️⃣  Checking created files..."
ansible webservers -m shell -a "ls -la /tmp/ansible* /tmp/timestamp.txt 2>/dev/null || echo 'Some files may not exist'" -i $INVENTORY
echo ""

echo "7️⃣  Using become (sudo) - would need password..."
echo "   ansible webservers -m command -a 'tail /var/log/syslog' -b -K -i $INVENTORY"
echo ""

echo "✅ Advanced examples completed!"
echo "💡 Tip: Use -C flag for dry runs before executing commands"