---
- name: Install and configure Nginx website1
  hosts: web1
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Remove existing celebratian.com directory
      file:
        path: /var/www/celebratian.com
        state: absent

    - name: Copy celebratian.com website content
      copy:
        src: files/celebratian.com/
        dest: /var/www/celebratian.com/
        owner: www-data
        group: www-data
        mode: '0644'


    - name: Remove default nginx site from sites-enabled
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - Test nginx config
        - Reload nginx

    - name: Copy celebratian.com nginx config
      copy:
        src: files/celebratian.conf
        dest: /etc/nginx/sites-available/celebratian.com
        owner: root
        group: root
        mode: '0644'
      notify:
        - Test nginx config
        - Reload nginx

    - name: Enable celebratian.com site
      file:
        src: /etc/nginx/sites-available/celebratian.com
        dest: /etc/nginx/sites-enabled/celebratian.com
        state: link
        force: yes
      notify:
        - Test nginx config
        - Reload nginx

  handlers:
    - name: Test nginx config
      command: nginx -t

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded


- name: Install and configure Nginx website2
  hosts: web2
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
        

    - name: Remove existing itdefined.com directory
      file:
        path: /var/www/itdefined.com
        state: absent

    - name: Copy itdefined.com website content
      copy:
        src: files/itdefined.com/
        dest: /var/www/itdefined.com/
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Remove default nginx site from sites-enabled
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - Test nginx config
        - Reload nginx


    - name: Copy itdefined.com nginx config
      copy:
        src: files/itdefined.conf
        dest: /etc/nginx/sites-available/itdefined.com
        owner: root
        group: root
        mode: '0644'
      notify:
        - Test nginx config
        - Reload nginx
      

    - name: Enable itdefined.com site
      file:
        src: /etc/nginx/sites-available/itdefined.com
        dest: /etc/nginx/sites-enabled/itdefined.com
        state: link
        force: yes
      notify:
        - Test nginx config
        - Reload nginx

  handlers:
    - name: Test nginx config
      command: nginx -t

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded